/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LogographyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  serverUrl: "https://logographyapp.com",
  apiKey: "",
  userId: "",
  enableAuthorMemory: true,
  shareMemoryWithAI: true,
  userName: ""
};
var LogographySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Logography Settings" });
    containerEl.createEl("h3", { text: "Server" });
    new import_obsidian.Setting(containerEl).setName("Server URL").setDesc("Your Logography server address").addText(
      (text) => text.setPlaceholder("https://logographyapp.com").setValue(this.plugin.settings.serverUrl).onChange(async (value) => {
        this.plugin.settings.serverUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("Your Logography API key (stored in plugin settings)").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("logography-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("User ID").setDesc("Your Logography account ID (auto-assigned on signup)").addText(
      (text) => text.setPlaceholder("obsidian_user_abc123").setValue(this.plugin.settings.userId).onChange(async (value) => {
        this.plugin.settings.userId = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Session" });
    new import_obsidian.Setting(containerEl).setName("Your Name").setDesc("How the guide addresses you (optional)").addText(
      (text) => text.setPlaceholder("Enter your name").setValue(this.plugin.settings.userName).onChange(async (value) => {
        this.plugin.settings.userName = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Privacy" });
    new import_obsidian.Setting(containerEl).setName("Enable Author Memory").setDesc("Track patterns across sessions (stored locally only)").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableAuthorMemory).onChange(async (value) => {
        this.plugin.settings.enableAuthorMemory = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Share Memory with AI").setDesc("Include cross-session memory in AI prompts").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.shareMemoryWithAI).onChange(async (value) => {
        this.plugin.settings.shareMemoryWithAI = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Status" });
    const statusEl = containerEl.createDiv();
    statusEl.createEl("p", {
      text: `Server: ${this.plugin.settings.serverUrl || "Not configured"}`
    });
    statusEl.createEl("p", {
      text: `User ID: ${this.plugin.settings.userId || "Not configured"}`
    });
  }
};

// src/views/LogographyView.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_LOGOGRAPHY = "logography-chat-view";
var LogographyView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.sessionId = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_LOGOGRAPHY;
  }
  getDisplayText() {
    return "Logography";
  }
  getIcon() {
    return "brain";
  }
  async onOpen() {
    const container = this.contentEl;
    container.empty();
    container.addClass("logography-chat-container");
    const header = container.createDiv("logography-header");
    header.createEl("span", { text: "Logography", cls: "logography-title" });
    const newSessionBtn = header.createEl("button", {
      text: "New Session",
      cls: "logography-new-session-btn"
    });
    newSessionBtn.addEventListener("click", () => this.startNewSession());
    this.phaseEl = container.createDiv("logography-phase-indicator");
    this.updatePhaseIndicator("I", "opening");
    this.messagesEl = container.createDiv("logography-messages");
    const inputArea = container.createDiv("logography-input-area");
    this.inputEl = inputArea.createEl("textarea", {
      cls: "logography-input",
      attr: {
        placeholder: "Share a dream, a problem, or a question...",
        rows: "2"
      }
    });
    const sendBtn = inputArea.createEl("button", {
      text: "Send",
      cls: "logography-send-btn mod-cta"
    });
    sendBtn.addEventListener("click", () => this.handleSend());
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.handleSend();
      }
    });
    this.inputEl.addEventListener("input", () => {
      this.inputEl.style.height = "auto";
      this.inputEl.style.height = Math.min(this.inputEl.scrollHeight, 120) + "px";
    });
    setTimeout(() => this.inputEl.focus(), 50);
    this.addMessage("assistant", "What would you like to explore today? A dream, a problem, a question about yourself?");
  }
  async onClose() {
    if (this.sessionId && this.plugin.settings.enableAuthorMemory) {
      try {
        const summary = await this.plugin.server.reviewSession();
        if (summary.summary) {
          this.plugin.authorMemory.queueUpdate(summary.summary);
        }
      } catch (e) {
      }
    }
  }
  async handleSend() {
    const text = this.inputEl.value.trim();
    if (!text)
      return;
    if (this.detectCrisis(text)) {
      this.addMessage("assistant", "I want to pause here. If you're in crisis, please reach out to the 988 Suicide & Crisis Lifeline (call or text 988) or the Crisis Text Line (text HOME to 741741). You don't have to face this alone.");
      this.inputEl.value = "";
      return;
    }
    this.addMessage("user", text);
    this.inputEl.value = "";
    this.inputEl.style.height = "auto";
    try {
      const thinkingEl = this.addMessage("assistant", "...");
      thinkingEl.addClass("logography-thinking");
      const response = await this.plugin.server.sendMessage(text);
      thinkingEl.remove();
      this.addMessage("assistant", response.text);
      this.updatePhaseIndicator(response.phase, response.step);
      this.sessionId = response.session_id;
      if (this.plugin.settings.enableAuthorMemory) {
        await this.saveToVault(text, response);
      }
    } catch (error) {
      const thinking = this.messagesEl.querySelector(".logography-thinking");
      if (thinking)
        thinking.remove();
      const errorMsg = error instanceof Error ? error.message : "Connection error";
      this.addMessage("assistant", errorMsg);
    }
  }
  addMessage(role, text) {
    const msgEl = this.messagesEl.createDiv(`logography-message ${role}`);
    msgEl.textContent = text;
    this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
    return msgEl;
  }
  updatePhaseIndicator(phase, step) {
    const phaseNames = {
      I: "Terrain",
      II: "Scenes",
      III: "Analysis",
      IV: "Cross-Examination",
      V: "Integration",
      terrain: "Terrain",
      scenes: "Scenes",
      diagram: "Analysis",
      cross_exam: "Cross-Examination",
      integration: "Integration"
    };
    const phaseName = phaseNames[phase] || phase;
    const stepName = step.replace(/_/g, " ");
    this.phaseEl.textContent = `Phase ${phase}: ${phaseName} \u2014 ${stepName}`;
  }
  async saveToVault(userMessage, response) {
    try {
      const sessionFile = `Logography/Sessions/${(/* @__PURE__ */ new Date()).toISOString().slice(0, 10)}-session.md`;
      const existing = this.plugin.vaultStorage.getVault().getAbstractFileByPath(sessionFile);
      const entry = `

**You:** ${userMessage}

**Guide:** ${response.text}
`;
      if (existing) {
        await this.plugin.vaultStorage.getVault().process(existing, (data) => data + entry);
      } else {
        const header = `# Logography Session \u2014 ${(/* @__PURE__ */ new Date()).toLocaleDateString()}

*Phase: ${response.phase} | Step: ${response.step}*
`;
        await this.plugin.vaultStorage.getVault().create(sessionFile, header + entry);
      }
    } catch (e) {
    }
  }
  startNewSession() {
    this.sessionId = null;
    this.messagesEl.empty();
    this.updatePhaseIndicator("I", "opening");
    this.addMessage("assistant", "What would you like to explore today? A dream, a problem, a question about yourself?");
  }
  // Sleepy UI: expose focus for Quick Capture command
  focusInput() {
    if (this.inputEl) {
      this.inputEl.focus();
    }
  }
  detectCrisis(text) {
    const crisisKeywords = [
      "kill myself",
      "suicide",
      "want to die",
      "end my life",
      "self harm",
      "hurting myself",
      "no reason to live",
      "better off dead",
      "can't go on",
      "give up on life"
    ];
    const lower = text.toLowerCase();
    return crisisKeywords.some((keyword) => lower.includes(keyword));
  }
};

// src/server/LogographyServer.ts
var import_obsidian3 = require("obsidian");
var LogographyServer = class {
  constructor(serverUrl, apiKey, userId) {
    this.serverUrl = serverUrl.replace(/\/$/, "");
    this.apiKey = apiKey;
    this.userId = userId;
  }
  updateConfig(serverUrl, apiKey) {
    this.serverUrl = serverUrl.replace(/\/$/, "");
    this.apiKey = apiKey;
  }
  async request(method, path, body) {
    const params = {
      url: `${this.serverUrl}${path}`,
      method,
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.apiKey}`
      },
      contentType: "application/json"
    };
    if (body) {
      params.body = JSON.stringify(body);
    }
    const response = await (0, import_obsidian3.requestUrl)(params);
    if (response.status === 401) {
      throw new Error("Invalid API key. Check your Logography settings.");
    }
    if (response.status === 403) {
      throw new Error("Account inactive or session limit reached.");
    }
    if (response.status === 429) {
      throw new Error("Rate limited. Please wait a moment.");
    }
    if (response.status >= 500) {
      throw new Error("Server error. Please try again later.");
    }
    if (response.status !== 200) {
      throw new Error(`Request failed (${response.status})`);
    }
    return response.json;
  }
  async sendMessage(message) {
    return this.request("POST", "/api/chat", {
      user_id: this.userId,
      message
    });
  }
  async newSession() {
    return this.request("POST", "/api/session/new", {
      user_id: this.userId
    });
  }
  async getSessionStatus() {
    return this.request("GET", `/api/session/${this.userId}`);
  }
  async listSessions() {
    return this.request("GET", `/api/sessions/${this.userId}`);
  }
  async loadSession(sessionId) {
    return this.request("POST", "/api/sessions/load", {
      user_id: this.userId,
      session_id: sessionId
    });
  }
  async reviewSession() {
    return this.request("POST", `/api/review/${this.userId}`);
  }
  async health() {
    return this.request("GET", "/api/health");
  }
};

// src/storage/VaultStorage.ts
var import_obsidian4 = require("obsidian");
var SESSIONS_FOLDER = "Logography/Sessions";
var PATTERNS_FOLDER = "Logography/Patterns";
var VaultStorage = class {
  constructor(app) {
    this.vault = app.vault;
  }
  getVault() {
    return this.vault;
  }
  async ensureFolders() {
    await this.ensureFolder(SESSIONS_FOLDER);
    await this.ensureFolder(PATTERNS_FOLDER);
  }
  async ensureFolder(path) {
    const existing = this.vault.getAbstractFileByPath(path);
    if (!existing) {
      await this.vault.createFolder(path);
    }
  }
  // Save author memory summary to patterns folder
  async saveAuthorMemory(summary) {
    const filepath = `${PATTERNS_FOLDER}/author-memory.md`;
    const content = `# Logography \u2014 Author Memory

*Auto-generated cross-session pattern summary. Updated after each session.*

${summary}

---
*Last updated: ${(/* @__PURE__ */ new Date()).toISOString()}*
`;
    const existing = this.vault.getAbstractFileByPath(filepath);
    if (existing instanceof import_obsidian4.TFile) {
      await this.vault.modify(existing, content);
    } else {
      await this.vault.create(filepath, content);
    }
  }
  // Load existing author memory
  async loadAuthorMemory() {
    const filepath = `${PATTERNS_FOLDER}/author-memory.md`;
    const file = this.vault.getAbstractFileByPath(filepath);
    if (file instanceof import_obsidian4.TFile) {
      const content = await this.vault.read(file);
      const match = content.match(/\*Auto-generated.*?\*[\s\S]*?(?=\n\n---)/);
      return match ? match[0].replace(/\*Auto-generated.*?\*\n\n/, "").trim() : "";
    }
    return "";
  }
};

// src/storage/AuthorMemory.ts
var AuthorMemory = class {
  constructor(storage) {
    this.summary = "";
    this.updateQueue = Promise.resolve();
    this.storage = storage;
  }
  async load() {
    this.summary = await this.storage.loadAuthorMemory();
  }
  getSummary() {
    return this.summary;
  }
  // Queue an update to prevent race conditions
  queueUpdate(newSummary) {
    this.updateQueue = this.updateQueue.catch(() => {
    }).then(async () => {
      if (newSummary && newSummary !== this.summary) {
        this.summary = newSummary;
        await this.storage.saveAuthorMemory(newSummary);
      }
    });
  }
  // Build context string for prompt injection
  getContextForPrompt(enabled, shared) {
    if (!enabled) {
      return "Cross-session memory: disabled by user settings.";
    }
    if (!shared) {
      return "Cross-session memory: stored locally but not shared with AI.";
    }
    if (!this.summary.trim()) {
      return "Cross-session memory: none yet (first session).";
    }
    return `Cross-session memory (patterns from previous sessions):
${this.summary.trim()}`;
  }
  // Build the prompt instruction for updating memory
  getUpdateInstruction() {
    return `Based on this session, update the author memory summary. 
Capture enduring patterns, recurring beliefs, progress made, and areas still under exploration. 
Keep it under 200 words. Focus on what would be useful context for future sessions.

Previous memory summary:
${this.summary || "(none yet)"}

Provide ONLY the updated summary text, no preamble.`;
  }
};

// src/main.ts
var LogographyPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    if (!this.settings.userId) {
      this.settings.userId = `obsidian_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
      await this.saveSettings();
    }
    this.server = new LogographyServer(
      this.settings.serverUrl,
      this.settings.apiKey,
      this.settings.userId
    );
    this.vaultStorage = new VaultStorage(this.app);
    this.authorMemory = new AuthorMemory(this.vaultStorage);
    await this.vaultStorage.ensureFolders();
    if (this.settings.enableAuthorMemory) {
      await this.authorMemory.load();
    }
    this.registerView(VIEW_TYPE_LOGOGRAPHY, (leaf) => new LogographyView(leaf, this));
    this.addRibbonIcon("brain", "Open Logography", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-logography",
      name: "Open Logography",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "new-logography-session",
      name: "Logography: New Session",
      callback: () => {
        this.app.workspace.getLeavesOfType(VIEW_TYPE_LOGOGRAPHY).forEach((leaf) => leaf.detach());
        this.activateView();
      }
    });
    this.addCommand({
      id: "quick-capture",
      name: "Logography: Quick Capture",
      callback: () => this.quickCapture()
    });
    this.addSettingTab(new LogographySettingTab(this.app, this));
    console.log("Logography loaded \u2014 Philosophical Midwifery for Obsidian");
  }
  async onunload() {
    console.log("Logography unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.server) {
      this.server.updateConfig(this.settings.serverUrl, this.settings.apiKey);
    }
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_LOGOGRAPHY)[0];
    if (!leaf) {
      leaf = workspace.getRightLeaf(false) || workspace.getLeaf();
      await leaf.setViewState({ type: VIEW_TYPE_LOGOGRAPHY, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  // Sleepy UI: open pane and focus input in one action
  async quickCapture() {
    await this.activateView();
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_LOGOGRAPHY);
    if (leaves.length > 0) {
      const view = leaves[0].view;
      view.focusInput();
    }
  }
};
